### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by StreetStrider** [shaunxcode/edn-cpp#8]
What is the license of this lib?

**Comment by shaunxcode** [comment]
Good question - it was meant to be MIT licensed once I got around to "Releasing" it. However life happened and I have not had time to work on it. I will add the license file if you are interested in forking/working on it.

**Comment by shaunxcode** [comment]
Added said license!

**Comment by StreetStrider** [comment]
@shaunxcode, thanks for adding.
As far as I googled, this is the only edn lib for C++. edn is perspective stuff and I'm going to use this lib. Thanks for your work.

**Comment by shaunxcode** [comment]
no problem, I tried to bring it to the point it was useful (I wrote a
datomic command line repl for instance) - I will be interested to see what
you do with it!
